name: å•å…ƒæµ‹è¯•
run-name: ${{ github.actor }} è¿›è¡Œäº†æäº¤ï¼Œè¿›è¡Œæµ‹è¯• ğŸš€
on: [push]
jobs:
  Run-Vitest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: è¿›è¡Œæµ‹è¯•
        run: |
          ls ${{ github.workspace }}
          npm ci
          npm install vitest
          npm run test